apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-x7i2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-x7i2
    app.kubernetes.io/part-of: tkrw-pr714-0075-0049-app
  name: devfile-sample-x7i2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-x7i2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-x7i2
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0049-tenant/tkrw-pr714-0075-0049-app/devfile-sample-x7i2@sha256:f1791ec5a3a6894c2454a0096b529fe66034591b4d14aa7e0b5a556f63e871ce
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
